# Generated by Django 4.1 on 2024-03-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=32, unique=True)),
                ('u_password', models.CharField(max_length=256)),
                ('u_mail', models.CharField(max_length=256)),
                ('is_super', models.BooleanField(default=False)),
            ],
        ),
    ]
