# Generated by Django 4.1 on 2024-03-12 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user_avatar_user_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_mail',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
