# Generated by Django 4.1 on 2024-03-12 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_u_id_alter_user_u_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/avatar/avatar.png', null=True, upload_to='static/avatar/'),
        ),
    ]
