# Generated by Django 4.1 on 2024-03-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_blog_id_alter_comment_u_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog_id',
            field=models.IntegerField(null=True),
        ),
    ]
