# Generated by Django 4.1 on 2024-03-13 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
