# Generated by Django 4.1 on 2024-03-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
